### ISSUE TITLE
Recent donations stopped working

### ISSUE THREAD

**Issue by adinaelisheva** [Ganon11/ExtraLifeWidgets#18]
![image](https://cloud.githubusercontent.com/assets/3931713/10298831/fdb16042-6bb0-11e5-81aa-9e345dbe668d.png)

:sob: :cry: :crying_cat_face:

**Comment by karantza** [comment]
I do not know how to use github :(  But yeah, this is fixed.

**Comment by arubinoff** [comment]
can you attach a screenshot?
